Dc coverage to publication tag
BIBSYSDEV/nva-fetch-doi pull request #108
Opened 2021-02-19 12:36 UTC by janbj

2021-02-19 13:00 UTC, axthosarouris requested changes

2021-02-19 13:00 UTC, axthosarouris commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +                .withDate(new PublicationDate.Builder()
variable

2021-02-19 13:02 UTC, axthosarouris commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +    public void test(String html, CreatePublicationRequest expectedRequest) throws IOException {
test naming

2021-02-19 13:06 UTC, brinxmat requested changes

2021-02-19 13:06 UTC, brinxmat commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        String date = String.join("-", year, month, day);
Extract as named method, it is an annoyance — use now()

2021-02-19 13:06 UTC, brinxmat commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        String year = "2021";
Extract as method, use now()

2021-02-19 13:06 UTC, brinxmat commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        CreatePublicationRequest request = new CreatePublicationRequest();
Extract method

2021-02-19 13:06 UTC, brinxmat commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        CreatePublicationRequest request = new CreatePublicationRequest();
Extract method

2021-02-19 13:06 UTC, brinxmat commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        CreatePublicationRequest request = new CreatePublicationRequest();
Extract methods

2021-02-19 13:06 UTC, brinxmat commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        CreatePublicationRequest request = new CreatePublicationRequest();
Extract method

2021-02-22 10:52 UTC, janbj commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        String year = "2021";
Why is it better to use now()?

2021-02-22 10:53 UTC, janbj commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        CreatePublicationRequest actual = request.get();
What warning?

2021-02-22 11:51 UTC, brinxmat requested changes

2021-02-22 11:51 UTC, brinxmat commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +                        "dc.contributor", name),
Still prefer constants

2021-02-22 11:51 UTC, brinxmat commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +        var body = getBody("/" + filename);
I still expect constants :)

2021-02-22 13:51 UTC, brinxmat approved these changes

2021-02-22 14:35 UTC, axthosarouris approved these changes

2021-02-26 06:43 UTC, merged