Add fix
BIBSYSDEV/nva-fetch-doi pull request #140
Opened 2021-03-28 09:32 UTC by brinxmat

- Unfortunately, something went very wrong in our process here — let's not repeat this, tips about what went wrong?
- Added tests to describe what is expected
- Added refactored code to match

2021-03-29 08:32 UTC, mattiahj commented
Both Master and Develop seem to build fine, so maybe the error is here?

2021-03-29 08:38 UTC, mattiahj commented on doi-proxy/src/test/java/no/unit/nva/doi/CrossRefClientTest.java
> +        assertThat(actual, containsString(MISSING_CROSSREF_TOKENS_ERROR_MESSAGE));
This does not assert what the name of the test implies it should assert, does it?

2021-03-29 13:48 UTC, brinxmat commented on doi-proxy/src/main/java/no/unit/nva/doi/CrossRefClient.java
> +
Before I refactor this, the previous functionality viewed misconfiguration of the secrets as OK and defaulted to the open Crossref API if no secret was found…do we still want this?

2021-03-29 15:41 UTC, axthosarouris requested changes
Temporary block because I want to check if the code can be made simpler. I will check it tomorrow first thing in the morning

2021-03-30 08:58 UTC, axthosarouris approved these changes

2021-03-30 11:11 UTC, merged