Smile 1223 template scopus s3 and unzipper
BIBSYSDEV/nva-fetch-doi pull request #224
Opened 2022-01-19 07:53 UTC by nraanes

Tuned role policy for nva-scopus function and unzipper-function. Unzipper should now be (almost) PEP8 compliant.

2022-01-19 09:04 UTC, anetteOlli approved these changes

2022-01-19 09:54 UTC, axthosarouris requested changes

2022-01-19 09:54 UTC, axthosarouris commented on template.yaml
> +                  - !Sub 'arn:aws:s3:::${ScopusZipBucket}-${AWS::AccountId}/*'
This is a reference to the bucket's name  (i.e.,  !GetAtt ScopuZipBucket.Name). Adding the account id is not necessary

2022-01-19 09:55 UTC, axthosarouris commented on template.yaml
> +                  - !Sub 'arn:aws:s3:::${ScopusZipBucket}-${AWS::AccountId}/*'
It is best to use the parameters as little as possible and use the !Ref and !GetAtt functions using the actual AWS entities. This gives more flexibility

2022-01-19 12:05 UTC, nraanes commented on template.yaml
> +                  - !Sub 'arn:aws:s3:::${ScopusZipBucket}/*'
When I test creating stack from template I run into this error:

_Circular dependency between resources: [ScopusUnzipperFunctionUnzipEventPermission, ScopusUnzipperFunction, ScopusZipBucket, ScopusUnzipperFunctionRole]_

However, when not referencing the actual bucket in the policy statements the stack is created: `'arn:aws:s3:::${ScopusZipBucketName}-${AWS::AccountId}/*'`

2022-01-19 14:45 UTC, nraanes commented on template.yaml
> +                  - !Sub 'arn:aws:s3:::${ScopusZipBucket}/*'
I seem to have used ${} wrong. Will look at this again tomorrow.

2022-01-20 09:11 UTC, nraanes commented on template.yaml
> +      PolicyName: !Sub ScopusBucketsAccessPolicy-${AWS::StackName}
Bugfix: DefaultLambdaPermissions-policy was overwritten

2022-01-20 09:12 UTC, brinxmat approved these changes

2022-01-20 09:15 UTC, axthosarouris approved these changes

2022-01-20 09:16 UTC, merged

2022-01-20 09:16 UTC, anetteOlli approved these changes