NP-3598: refactor main title test
BIBSYSDEV/nva-fetch-doi pull request #248
Opened 2022-02-08 13:19 UTC by axthosarouris

2022-02-08 14:10 UTC, brinxmat requested changes

2022-02-08 14:10 UTC, brinxmat commented on create-publication-from-scopus/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +            .filter(t -> t.getOriginal().equals(YesnoAtt.Y))
Flip the equality

2022-02-08 14:14 UTC, anetteOlli approved these changes

2022-02-08 14:17 UTC, gregorgabriel approved these changes

2022-02-09 12:09 UTC, brinxmat approved these changes

2022-02-09 12:37 UTC, merged