Smile 1329 fetch book publication context
BIBSYSDEV/nva-fetch-doi pull request #260
Opened 2022-02-11 13:10 UTC by gregorgabriel

Her kommer første versjon av ei boka.
PublicationContext Book is implemented. Viktig detajl er her Publisher i publication-channels .
(bookSeries) er fortsatt null. Det kommer på neste iterasjon.

2022-02-14 11:51 UTC, axthosarouris commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/PublicationContextCreator.java
> +        List<String> isbnList = new ArrayList<>();
Collections.emptyList()

2022-02-14 13:11 UTC, axthosarouris commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +    public void getPublisherIdFromPublicationChannelsByGivenPublisherName()
testing name format: shouldReturnPublisherId....

2022-02-15 16:26 UTC, brinxmat requested changes

2022-02-15 16:26 UTC, brinxmat commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/PublicationContextCreator.java
> +                .map(srcTyp -> BOOK.equals(ScopusSourceType.valueOfCode(srcTyp)))
srcTyp[e]

2022-02-15 16:26 UTC, brinxmat commented on create-publication-from-scopus/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +        String actualPublisherName = ((UnconfirmedPublisher) actualPublisher).getName();
var

2022-02-15 16:26 UTC, brinxmat commented on metadata-transformer/src/main/java/no/unit/nva/metadata/service/MetadataService.java
> +            .addQueryParameter("query", searchTerm)
Constant query

2022-02-17 09:52 UTC, gregorgabriel commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/PublicationContextCreator.java
> +        List<String> isbnList = new ArrayList<>();
ok

2022-02-17 09:53 UTC, gregorgabriel commented on metadata-transformer/src/test/java/no/unit/nva/metadata/service/MetadataServiceTest.java
> +    public void getPublisherIdFromPublicationChannelsByGivenPublisherName()
ok

2022-02-17 09:53 UTC, gregorgabriel commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/PublicationContextCreator.java
> +                .map(srcTyp -> BOOK.equals(ScopusSourceType.valueOfCode(srcTyp)))
ok

2022-02-17 09:54 UTC, gregorgabriel commented on create-publication-from-scopus/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +        String actualPublisherName = ((UnconfirmedPublisher) actualPublisher).getName();
ok

2022-02-17 09:55 UTC, gregorgabriel commented on metadata-transformer/src/main/java/no/unit/nva/metadata/service/MetadataService.java
> +            .addQueryParameter("query", searchTerm)
ok

2022-02-17 20:26 UTC, brinxmat approved these changes

2022-02-18 07:41 UTC, gregorgabriel commented on create-publication-from-scopus/src/test/java/no/sikt/nva/scopus/exception/ExceptionsTest.java
> +    public void canCreateUnsupportedScrTypeExcetption() {
You are (selvfølgelig) right. Testen trengs ikke og er slettet.

2022-02-18 07:46 UTC, merged