Smile 1379 join duplicate authors
BIBSYSDEV/nva-fetch-doi pull request #291
Opened 2022-03-08 15:47 UTC by anetteOlli

2022-03-09 09:27 UTC, axthosarouris approved these changes

2022-03-09 09:33 UTC, nraanes approved these changes
Nice 👍

2022-03-09 21:30 UTC, brinxmat requested changes

2022-03-09 21:30 UTC, brinxmat commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/ContributorExtractor.java
> +    private Contributor newContributorFromExistingContributorWithAdditionalAffiliation(Contributor existingContributor,
cloneContributorAddingAffiliation

2022-03-09 21:30 UTC, brinxmat commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/ContributorExtractor.java
> +    private boolean contributorEqualsCollaboration(CollaborationTp collaboration, Contributor contributor) {
isSameSequenceElement

2022-03-09 21:30 UTC, brinxmat commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/ContributorExtractor.java
> +    private boolean contributorEqualsAuthorTp(AuthorTp author, Contributor contributor) {
isSamePerson

2022-03-10 07:20 UTC, gregorgabriel approved these changes

2022-03-10 07:20 UTC, gregorgabriel commented on create-publication-from-scopus/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +    void itShouldNotOutPutDuplicateContributors() throws IOException {
shouldHaveNoDuplicateContributers

2022-03-10 07:20 UTC, gregorgabriel commented on create-publication-from-scopus/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +    private void isNotDuplicate(List<Integer> sequenceNumbers, List<String> orcids, Contributor contributor) {
isNoDuplicate ??? or isNotDuplicated

2022-03-10 08:22 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/ContributorExtractor.java
> +    private Contributor newContributorFromExistingContributorWithAdditionalAffiliation(Contributor existingContributor,
supert, det er et bedre navn ja.
Fikset

2022-03-10 08:23 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/ContributorExtractor.java
> +    private boolean contributorEqualsCollaboration(CollaborationTp collaboration, Contributor contributor) {
Supert.
Vurderte contributorCorrespondsToCollaboration, men vi har jo allerede noe som heter corresponding contributor, så det hadde bare blitt verre.
fikset

2022-03-10 08:23 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/ContributorExtractor.java
> +    private boolean contributorEqualsAuthorTp(AuthorTp author, Contributor contributor) {
Fikset

2022-03-10 08:24 UTC, anetteOlli commented on create-publication-from-scopus/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +    void itShouldNotOutPutDuplicateContributors() throws IOException {
Fikset

2022-03-10 08:24 UTC, anetteOlli commented on create-publication-from-scopus/src/test/java/no/sikt/nva/scopus/ScopusHandlerTest.java
> +    private void isNotDuplicate(List<Integer> sequenceNumbers, List<String> orcids, Contributor contributor) {
Lol, fikset

2022-03-10 10:29 UTC, brinxmat approved these changes

2022-03-10 10:48 UTC, merged