Smile 1395 extract language from scopus
BIBSYSDEV/nva-fetch-doi pull request #296
Opened 2022-03-11 09:43 UTC by anetteOlli

2022-03-11 11:03 UTC, brinxmat requested changes

2022-03-11 11:47 UTC, gregorgabriel approved these changes

2022-03-11 12:20 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/LanguageExtractor.java
> +        } else {
fikset

2022-03-15 07:10 UTC, nraanes approved these changes

2022-03-15 10:31 UTC, brinxmat approved these changes

2022-03-16 08:53 UTC, merged