use latest commons
BIBSYSDEV/nva-fetch-doi pull request #302
Opened 2022-04-13 12:28 UTC by axthosarouris

2022-04-19 14:33 UTC, brinxmat requested changes

2022-04-20 11:36 UTC, axthosarouris commented on settings.gradle
> +//include 'fetch-doi-testing'
I should include them. It is still work in progress. I asked for a review by mistake

2022-04-20 13:29 UTC, axthosarouris commented on create-publication-from-doi/src/test/java/no/unit/nva/doi/fetch/MainHandlerTest.java
> +        assertThat(logger.getMessages(),containsString("Missing host for creating URI"));
Assert that the message of the UriWrapper is logged

2022-04-20 16:20 UTC, brinxmat approved these changes

2022-04-20 20:39 UTC, merged