Smile 1616 use cristind id to substitute contributor
BIBSYSDEV/nva-fetch-doi pull request #321
Opened 2022-06-23 07:59 UTC by anetteOlli

2022-06-23 08:01 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/model/cristin/Affiliation.java
> +package no.sikt.nva.scopus.conversion.model.cristin;
Siden dette har blitt kopier fra nva-cristin-service, burde denne vært tatt inni  nva-datamodel slik at vi kan vi kan importere dette istedet for copy-pase.

2022-06-23 09:43 UTC, brinxmat requested changes

2022-06-23 11:20 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/CristinConnection.java
> +        return gson.fromJson(json, Person.class);
Are you referring to the "new" keyword that places object on the heap and does not support inversion of dependencies?
Are we using jackson incorrectly? ended up with var objectMapper = new ObjectMapper.

2022-06-23 11:29 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/CristinConnection.java
> +        }
I guess we can follow redirects, but at the same time, if we are ending up with somewhere else than where nva-cristin-service is running, I can't imagine we get something that can be converted to a Person.class.
Isn't the handler also an aws handler that will in practise never return "busy try again later"

2022-06-23 11:30 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/model/cristin/Role.java
> +        return Objects.nonNull(labels) ? labels : Collections.emptyMap();
This is also copy paste code from nva-cristin-service. But will fix.

2022-06-23 11:36 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/ContributorExtractor.java
> +            TypedValue::getValue).orElse(StringUtils.EMPTY_STRING);
Fikset

2022-06-23 11:37 UTC, anetteOlli commented on create-publication-from-scopus/src/main/java/no/sikt/nva/scopus/conversion/CristinConnection.java
> +        return gson.fromJson(json, Person.class);
Switched to jackson

2022-06-23 16:23 UTC, brinxmat approved these changes

2022-06-24 09:12 UTC, gregorgabriel approved these changes
no further comments. Bra jobber

2022-06-27 07:35 UTC, merged