Adding name from crossref.author.affiliation to publication.contribut…
BIBSYSDEV/nva-fetch-doi pull request #89
Opened 2021-01-26 14:00 UTC by svenngjeto

Adding name from crossref.author.affiliation to publication.contributor.affiliation.labels with 'en' as default language tag

2021-01-26 15:07 UTC, axthosarouris commented on doi-transformer/src/main/java/no/unit/nva/doi/transformer/CrossRefConverter.java
> +        if (nonNull(author.getAffiliation())) {
refactor to method

2021-01-26 15:51 UTC, brinxmat requested changes
See first reviewer's comment

2021-01-27 08:09 UTC, svenngjeto commented on doi-transformer/src/main/java/no/unit/nva/doi/transformer/CrossRefConverter.java
> +        if (nonNull(author.getAffiliation())) {
Done!

2021-01-27 09:34 UTC, janbj commented on doi-transformer/src/main/java/no/unit/nva/doi/transformer/CrossRefConverter.java
> +                Map.of(DEFAULT_LANGUAGE_ENGLISH, crossrefAffiliations.stream().findFirst().get().getName());
Hva hvis det er flere?

2021-01-27 10:36 UTC, brinxmat requested changes

2021-01-27 10:36 UTC, brinxmat commented on doi-transformer/src/main/java/no/unit/nva/doi/transformer/CrossRefConverter.java
> +                Map.of(DEFAULT_LANGUAGE_ENGLISH, crossrefAffiliations.stream().findFirst().get().getName());
Enig, bare pøs alt over som en liste

2021-01-27 12:14 UTC, svenngjeto commented on doi-transformer/src/main/java/no/unit/nva/doi/transformer/CrossRefConverter.java
> +                Map.of(DEFAULT_LANGUAGE_ENGLISH, crossrefAffiliations.stream().findFirst().get().getName());
Sånn, nå tar den med seg alle affiliations - ikke bare første

2021-01-27 12:57 UTC, brinxmat approved these changes

2021-01-27 13:11 UTC, merged