Extract metadata from web
BIBSYSDEV/nva-fetch-doi pull request #95
Opened 2021-02-10 13:57 UTC by janbj

2021-02-10 14:23 UTC, brinxmat submitted a review, later dismissed

2021-02-11 07:19 UTC, axthosarouris requested changes
I get an error when I build it:

```
* What went wrong:
Execution failed for task ':create-publication-from-doi:pmdMain'.
> java.lang.NoClassDefFoundError: javax/ws/rs/NotFoundException
```

2021-02-11 07:19 UTC, axthosarouris commented on metadata-transformer/src/main/java/no/unit/nva/metadata/service/TranslatorService.java
> +    public void get(URI uri) throws URISyntaxException, IOException, ExtractionException {
method name: loadMetadataFromUri

2021-02-11 07:19 UTC, axthosarouris commented on metadata-transformer/src/main/java/no/unit/nva/metadata/service/TranslatorService.java
> +        try (TripleHandler handler = new ReportingTripleHandler(
the "new ReportingTripleHandler" should be refactored in a method

2021-02-11 09:21 UTC, axthosarouris requested changes

2021-02-11 09:21 UTC, axthosarouris commented on create-publication-from-doi/build.gradle
> +    compileOnly group: 'jakarta.ws.rs', name: 'jakarta.ws.rs-api', version: project.ext.jakartaVersion
put a because clause

2021-02-11 09:37 UTC, axthosarouris approved these changes

2021-02-11 09:40 UTC, merged